### ISSUE TITLE
UnboundLocalError: local variable 'selected_layer' referenced before assignment, YOLOv7 with Grad-CAM

### ISSUE THREAD

**Issue by Seema1997** [azizjadehs/YOLOv7-to-be-used-on-Grad-CAM#1]
Hi,
I am working on YOLOv7 and executing your code **YOLOv7-to-be-used-on-Grad-CAM**. I followed the given command in your repository " python src/main_script.py --yaml-path path/to/config.yaml --weights-path path/to/weights.pt --input-folder path/to/input/images --output-folder path/to/output/images --target-class-idx 1 --resize-dim 416 416 --selected-layer 104.rbr_dense.0"

in my case:
**"python src/main_script.py --yaml-path cfg/training/yolov7x.yaml --weights-path best_v7x.pt --input-folder data/test/images/  --output-folder data/test/ooutput --target-class-idx 1 --resize-dim 416 416 --selected-layer Conv"**

I want to generate heatmap of **any layer of the standard YOLOv7x model** (which i trained on my own dataset). But I am getting below error:

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Model configuration loaded successfully
/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:128: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11070). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
/opt/conda/lib/python3.8/site-packages/torch/functional.py:513: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3609.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
src/main_script.py:57: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(args.weights_path, map_location=device)
Weights loaded successfully
Model is in checkpoint and state_dict loaded
Model state_dict loaded successfully
Traceback (most recent call last):
  File "src/main_script.py", line 140, in <module>
    main()
  File "src/main_script.py", line 84, in main
    if selected_layer is None:
UnboundLocalError: local variable 'selected_layer' referenced before assignment

Can you please help in resolving this error? Any help would be appreciated.

Thnaks in advance!

**Comment by azizjadehs** [comment]
Hello, 

> in my case:
"python src/main_script.py --yaml-path cfg/training/yolov7x.yaml --weights-path best_v7x.pt --input-folder data/test/images/ --output-folder data/test/ooutput --target-class-idx 1 --resize-dim 416 416 --selected-layer Conv"

Apparently you didn't specify a selected layer in the last argument : `--selected-layer Conv`
You need to specify a layer you want to make a heatmap out of. in my case for using YOLOv7, the layer "104.rbr_dense.0" gave the best results.

I hope this will solve your problem.

**Comment by Seema1997** [comment]
Issue resolved.
Thank You!
